export const GET_PROFILES_REQ = "GET_PROFILES_REQ";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";

export const ADD_PROFILE_REQ = "ADD_PROFILE_REQ";
export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
export const ADD_PROFILE_FAIL = "ADD_PROFILE_FAIL";

export const CURRENT_PROFILE = "CURRENT_PROFILE";
